export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';
export const REQUEST_PEOPLE_PENDING = 'REQUEST_PEOPLE_PENDING';
export const REQUEST_PEOPLE_SUCCESS = 'REQUEST_PEOPLE_SUCCESS';
export const REQUEST_PEOPLE_FAILED = 'REQUEST_PEOPLE_FAILED';
